# Generated by Django 3.2.8 on 2021-10-22 14:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория оборудования')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Учредитель')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Учредитель',
                'verbose_name_plural': 'Учредители',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Логин')),
                ('password1', models.CharField(max_length=50, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=50, verbose_name='Подтверждение пароля')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapp.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Образовательное учреждение')),
                ('short_name', models.CharField(max_length=50, verbose_name='ОУ сокр.')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapp.founder', verbose_name='Учредитель')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Оборудование')),
                ('slug', models.SlugField(unique=True, verbose_name='Артикул')),
                ('price', models.CharField(default='предоставляется по запросу', max_length=50, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapp.category', verbose_name='Категория оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='ApplicationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapp.application', verbose_name='Заявка')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapp.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование заявок',
                'verbose_name_plural': 'Оборудование заявок',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='educational_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapp.institution', verbose_name='Образовательное учреждение'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regapp.user', verbose_name='Пользователь'),
        ),
    ]
